In [1]:
library(dplyr)

Warning message:
"package 'dplyr' was built under R version 3.3.3"
Attaching package: 'dplyr'

The following objects are masked from 'package:stats':

    filter, lag

The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union

In [2]:
palyer <- read.csv("player.csv")

In [3]:
player_data <- as.data.frame(palyer)

In [21]:
team <- read.csv("team.csv")

In [22]:
team <- as.data.frame(team)

In [4]:
player_data

      X     player_api_id player_name              overall_rating gk_rating
1      1    2625          Patryk Rachwal,18        63             153
2      2    2752          Diego Mainz              72              53
3      3    2768          Jose Dorado              75             128
4      4    2770          Ignacio Gonzalez         74             148
5      5    2790          Alberto Rey              73             144
6      6    2796          Javier Jimenez           69             340
7      7    2802          Pablo Hernandez          82             146
8      8    2805          Ruben Perez              76             141
9      9    2857          Ivan Perez               72             143
10    10    2862          Vicente Sanchez          76             146
11    11    2907          Gregory Lacombe          NA              NA
12    12    2973          Ugur Inceman             72             147
13    13    2977          David Rivas Rodriguez    82             104
14    14    2983          Jorge Molina             75             139
15    15    2984          Sergio Aragones          75             364
16    16    3140          Alexandre Hauw           69             136
17    17    3204          Marat Izmailov           81             156
18    18    3263          Kelly Berville           67             115
19    19    3264          Abdelmalek Cherrad       62              98
20    20    3316          Oscar Sanchez            71             108
21    21    3329          Vincent Euvrard          64             130
22    22    3377          Luca Belingheri          72             138
23    23    3441          Aleksander Radosavljevic 71             138
24    24    3512          Peter Halmosi            75             143
25    25    3517          Alexandr Kerzhakov       NA              NA
26    26    3520          Andrey Arshavin          86             159
27    27    4747          Lee Wilkie               73             128
28    28    4863          Boban Grncarov           66              54
29    29    4902          Iriney                   77             145
30    30    4939          Tim Clancy               64             116
...   ...   ...           ...                      ...            ...
11031 11031 701154        Kylian Mbappe Lottin     65             42
11032 11032 703659        Colin Trachsel           51             48
11033 11033 704523        Christopher Nkunku       62             43
11034 11034 705484        Eray Cumart              52             32
11035 11035 706985        Jordan Lyden             58             53
11036 11036 710807        Jonatan Montiel          67             47
11037 11037 715642        Aissa Laidouni           59             61
11038 11038 716998        Sebastien Lamonge        56             46
11039 11039 717248        Felipe Augusto           64             59
11040 11040 717270        Antoine Rabillard        61             56
11041 11041 717557        Levi Garcia              64             49
11042 11042 719413        Dorian Caddy             64             54
11043 11043 720738        Charles Traore           55             52
11044 11044 721133        Rafa Soares              70             60
11045 11045 722766        Charly Musonda           71             36
11046 11046 723037        Wanderson Lima           53             54
11047 11047 725718        Dennis van der Heijden   60             54
11048 11048 726956        Cedric Itten             54             41
11049 11049 728125        Christopher McLaughlin   50             49
11050 11050 728414        Justin Hoogma            59             54
11051 11051 728478        Kamil Jozwiak            56             54
11052 11052 730065        Jorge Intima             57             59
11053 11053 733787        Linus Obexer             51             45
11054 11054 742405        Tom Davies               51             56
11055 11055 743720        Charles Pickel           50             53
11056 11056 744907        Greg Taylor              53             57
11057 11057 746419        Francisco Afonso         59             42
11058 11058 748432        Fynn Arkenberg           58             46
11059 11059 750435        Rees Greenwood           60             48
11060 11060 750584        Alexandre Azevedo        58             54
      number_of_appearances
1      90
2      81
3      71
4      16
5      50
6       1
7     144
8     131
9       3
10     17
11      6
12     16
13      5
14     71
15     38
16     42
17     42
18     19
19      1
20      6
21     85
22      1
23     74
24      4
25     17
26     70
27     36
28     25
29     68
30     97
...   ...
11031  2
11032  1
11033  4
11034  4
11035  2
11036  1
11037  1
11038  1
11039  4
11040  1
11041  4
11042  3
11043  5
11044 15
11045 13
11046  7
11047  1
11048  4
11049  2
11050  1
11051  1
11052  1
11053  2
11054  1
11055  1
11056  1
11057  2
11058  2
11059  1
11060  1

In [23]:
team

    X   team_id team_name                    build_play chance_creation
1    1  1601    Ruch Chorzów                 139        186
2    2  1773    Oud-Heverlee Leuven          153        157
3    3  1957    Jagiellonia Bialystok        158        163
4    4  2033    S.C. Olhanense               147        165
5    5  2182    Lech Poznan                  176        196
6    6  2183    P. Warszawa                    0        180
7    7  2186    Cracovia                     125        168
8    8  4049    Tubize                         0          0
9    9  4064    Feirense                       0          0
10  10  4087    Évian Thonon Gaillard FC     156        180
11  11  4170    US Boulogne Cote D'Opale       0        165
12  12  6269    Novara                       179        172
13  13  6351    KAS Eupen                      0        160
14  14  6367    Uniao da Madeira               0          0
15  15  6391    GFC Ajaccio                  153        179
16  16  6403    FC Paços de Ferreira         142        170
17  17  6413    PEC Zwolle                   137        165
18  18  6421    Leixões SC                     0        165
19  19  6433    Go Ahead Eagles              160        132
20  20  6493    AC Bellinzona                  0        175
21  21  6547    FC Penafiel                  147        146
22  22  6601    FC Volendam                    0          0
23  23  6631    FC Dordrecht                 134        176
24  24  7730    FC Lausanne-Sports           141        164
25  25  7788    SC Cambuur                   136        159
26  26  7794    SC Bastia                    174        156
27  27  7819    SM Caen                      157        165
28  28  7841    Rio Ave FC                   157        180
29  29  7842    Estoril Praia                174        139
30  30  7844    Vitória Guimarães            131        179
... ... ...     ...                          ...        ...
270 270  10214  CD Nacional                  167        165
271 271  10215  Académica de Coimbra         150        172
272 272  10217  ADO Den Haag                 162        181
273 273  10218  Excelsior                    163        162
274 274  10219  RKC Waalwijk                 142        159
275 275  10228  SC Heerenveen                150        171
276 276  10229  AZ                           154        185
277 277  10233  Genoa                        184        182
278 278  10235  Feyenoord                    154        165
279 279  10238  Vitória Setúbal              149        165
280 280  10242  ES Troyes AC                 148        150
281 281  10243  FC Zürich                    157        165
282 282  10249  Montpellier Hérault SC       162        160
283 283  10251  Hibernian                    148        200
284 284  10252  Aston Villa                  170        185
285 285  10260  Manchester United            134        200
286 286  10261  Newcastle United             152        195
287 287  10264  SC Braga                     145        166
288 288  10265  Wisla Kraków                 135        183
289 289  10267  Valencia CF                  116        185
290 290  10268  Elche CF                     171        165
291 291  10269  VfB Stuttgart                168        200
292 292  10278  Hércules Club de Fútbol      154        178
293 293  10281  Real Valladolid              153        172
294 294 108893  AC Arles-Avignon             156        141
295 295 158085  FC Arouca                    174        160
296 296 177361  Termalica Bruk-Bet Nieciecza   0          0
297 297 188163  Tondela                        0          0
298 298 208931  Carpi                        190        160
299 299 274581  Royal Excel Mouscron         150        150
    defense_rating goals_scored
1   175            280
2   137            126
3   210            287
4   155            138
5   160            372
6   175            184
7   205            235
8     0             35
9     0             27
10  165            180
11  200             31
12  151             34
13  155             28
14    0             27
15  146             37
16  150            292
17  181            204
18   90             55
19  141             74
20  150            128
21  121             29
22    0             38
23  164             24
24  165             99
25  138            119
26  210            165
27  205            220
28  153            248
29  150            167
30  177            300
... ...            ...
270 156            332
271 151            240
272 173            366
273 106            154
274 150            153
275 183            470
276 184            492
277 154            392
278 160            489
279 140            238
280 140             71
281 163            468
282 210            344
283 200            259
284 145            335
285 163            582
286 161            324
287 150            398
288 205            332
289 175            484
290 158             65
291 175            415
292 160             36
293 161            170
294 158             21
295 113            101
296   0             33
297   0             34
298 141             37
299 140             71

# Q1: Which are the top 10 players by overall rating?

In [9]:
player_data %>%
select(player_name, overall_rating) %>%
arrange (desc(overall_rating)) %>% head(10)

   player_name       overall_rating
1  Lionel Messi      94
2  Gianluigi Buffon  93
3  Wayne Rooney      93
4  Cristiano Ronaldo 93
5  Xavi Hernandez    92
6  Gregory Coupet    92
7  Thierry Henry     91
8  John Terry        91
9  Iker Casillas     91
10 Alessandro Nesta  91

# Q2: Which are the top 10 goalkeepers by sum of gk attributes?

In [14]:
player_data %>%
select(player_name, gk_rating) %>%
arrange (desc(gk_rating)) %>% head(10)

   player_name       gk_rating
1  Gianluigi Buffon  449
2  Gregory Coupet    447
3  Petr Cech         445
4  Iker Casillas     442
5  Manuel Neuer      440
6  Julio Cesar       438
7  Sebastian Frey    437
8  Edwin van der Sar 436
9  David De Gea      429
10 Pepe Reina        428

# Q3: Which are the top 10 players by number of appearances (with any team they played with)?

In [15]:
player_data %>%
select(player_name, number_of_appearances) %>%
arrange (desc(number_of_appearances)) %>% head(10)

   player_name          number_of_appearances
1  Steve Mandanda       300
2  Stephane Ruffier     294
3  Gorka Iraizoz Moreno 286
4  Samir Handanovic     286
5  Hugo Lloris          282
6  Tim Howard           282
7  Joe Hart             275
8  Cedric Carrasso      268
9  Daniel Congre        262
10 Moussa Sissoko       260

# Q4: Which are the top 10 teams by sum of build up play attributes?

In [16]:
team %>%
select(team_name, build_play) %>%
arrange (desc(build_play)) %>% head(10)

   team_name                  build_play
1  Torino                     209
2  Udinese                    205
3  Fortuna Düsseldorf         198
4  Podbeskidzie Bielsko-Biala 193
5  Korona Kielce              192
6  Widzew Lódz                190
7  Widzew Lódz                190
8  Carpi                      190
9  FC Nantes                  189
10 Sassuolo                   188

# Q5: Which are the top 10 teams by sum of chance creation attributes?

In [17]:
team %>%
select(team_name, chance_creation) %>%
arrange (desc(chance_creation)) %>% head(10)

   team_name           chance_creation
1  Lazio               220
2  SV Werder Bremen    216
3  Napoli              215
4  Bayer 04 Leverkusen 210
5  Burnley             210
6  Cardiff City        210
7  Manchester City     210
8  Aberdeen            210
9  Rangers             210
10 Tottenham Hotspur   210

# Q6: Which are the top 10 teams by sum of defense attributes?

In [20]:
team %>%
select(team_name, defense_rating) %>%
arrange (desc(defense_rating)) %>% head(10)

   team_name             defense_rating
1  Jagiellonia Bialystok 210
2  SC Bastia             210
3  Zaglebie Lubin        210
4  Leicester City        210
5  Cardiff City          210
6  1. FC Kaiserslautern  210
7  Southampton           210
8  AS Nancy-Lorraine     210
9  Blackpool             210
10 Stade Brestois 29     210

# Q7: Which are the top 10 teams by number of scored goals?

In [24]:
team %>%
select(team_name, goals_scored) %>%
arrange (desc(goals_scored)) %>% head(10)

   team_name         goals_scored
1  FC Barcelona      849
2  Real Madrid CF    843
3  Celtic            695
4  FC Bayern Munich  653
5  PSV               652
6  Ajax              647
7  FC Basel          619
8  Manchester City   606
9  Chelsea           583
10 Manchester United 582